main: nz.tomay0.PixelProtect.PixelProtectPlugin
name: PixelProtect
version: 1
api-version: 1.15
description: >
  Grief Protection plugin
commands:
  protect:
    description: >
      Pixel Protect main command
    aliases:
      - pr